stages:
  - build
  - deploy_gcp

build_images:
  stage: build
  image: docker:20.10.16

  services:
    - docker:20.10.16-dind
  
  variables:
    DOCKER_TLS_CERTDIR: "/certs"

  before_script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

  script:
    - docker build -t pgomesd/app-prj-k8s-02:1.0 app/.
    - docker push pgomesd/app-prj-k8s-02:1.0

deploy_gcp:

  stage: deploy_gcp
  
  before_script:
    - chmod 400 $SSH_KEY

  script:
      - ssh -o StrictHostKeyChecking=no -i $SSH_KEY gcp@$SSH_SERVERIP "sudo rm -rf ./prj-k8s-02 && sudo git clone git@gitlab.com:pgomesd/prj-k8s-02.git && cd prj-k8s-02 && sudo chmod +x ./script.sh && ./script.sh"