apiVersion: v1
kind: PersistentVolume
metadata:
  name: localmysql
  labels:
    type: localmysql
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
   - ReadWriteOnce
  hostPath: 
    path: /database/

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: localmysql
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi